#!/usr/bin/env bash
# t1 — SEC-122 caras (a) y (b): los casos de R-046 (s1, s2, s2c) re-ejecutados contra el candidato final.
set -u
. /tmp/claude-1000/-home-juan-dev-ArnesJuan-v1-35/498ed6ee-03a0-4ce1-b63b-6612ed12e677/scratchpad/ev8/lib-sonda8.sh
proyecto_nuevo "$S/p1"
L="/dev/shm/arnes-r047-$$"; LS="/dev/shm/arnes-r047-src-$$"; LP="/dev/shm/arnes-r047-pself-$$"
OUT="$S/fuera-$$"; mkdir -p "$OUT"
ln -s "$P/requirements" "$L"; ln -s "$P/src" "$LS"; ln -s /proc/self "$LP"
ln -s "$P/requirements" "$OUT/lreq"; ln -s /proc/self/cwd "$OUT/lcwd"
trap 'rm -f "$L" "$LS" "$LP"; rm -rf "$OUT" "$PD"' EXIT
printf 'x\n' > "$S/ct.txt"
printf '%s' "${REQ_ROJO/en-revisión/completado}" > "$S/req-cerrado.txt"
echo "proyecto=$P"
echo "== Controles =="
j_edit "$P/requirements/REQ-900.md" "Estado: en-revisión" "Estado: completado"; fila "C1 Edit canónico cierra REQ rojo" "$J"
j_write "$P/src/a.ts" "$S/ct.txt"; fila "C2 Write canónico coordinadora src/a.ts" "$J"
j_bash "echo x > src/a.ts"; fila "C3 echo > src/a.ts" "$J"
j_write "$P/src/a.ts" "$S/ct.txt" "$P" desarrollador; fila "C4 Write src/a.ts desarrollador (allow)" "$J"
echo "== Cara (a): /dev/shm y /proc/self =="
j_edit "$L/REQ-900.md" "Estado: en-revisión" "Estado: completado"; fila "A1 Edit /dev/shm/<enlace>/REQ-900.md cierra" "$J"
j_edit "$L/REQ-900.md" "x-no-literal" "Estado: completado"; fila "A2 Edit no reconstruible (SEC-117) por /dev/shm" "$J"
j_write "$LS/a.ts" "$S/ct.txt"; fila "A3 Write /dev/shm/<enlace>/a.ts coordinadora" "$J"
j_bash "sed -i 's/en-revisión/completado/' $L/REQ-900.md"; fila "A4 sed -i por /dev/shm" "$J"
j_bash "echo x > $LS/a.ts"; fila "A5 echo > por /dev/shm" "$J"
j_write "$L/REQ-900.md" "$S/req-cerrado.txt"; fila "A6 Write REQ cerrado por /dev/shm" "$J"
j_edit "/proc/self/root$P/requirements/REQ-900.md" "Estado: en-revisión" "Estado: completado"; fila "A7 Edit /proc/self/root<raiz>/…" "$J"
j_bash "echo x > /proc/self/root$P/src/a.ts"; fila "A8 echo > /proc/self/root<raiz>/src/a.ts" "$J"
j_bash "echo x > /proc/self/cwd/src/a.ts"; fila "A9 echo > /proc/self/cwd/src/a.ts (cwd=raiz, Bash)" "$J"
j_write "/proc/self/cwd/src/a.ts" "$S/ct.txt"; fila "A10 Write /proc/self/cwd/src/a.ts (proceso del host)" "$J"
j_write "/proc/thread-self/cwd/src/a.ts" "$S/ct.txt"; fila "A11 Write /proc/thread-self/cwd/src/a.ts" "$J"
j_write "$LP/cwd/src/a.ts" "$S/ct.txt"; fila "A12 Write /dev/shm/<->/proc/self>/cwd/src/a.ts" "$J"
j_write "$OUT/lcwd/src/a.ts" "$S/ct.txt"; fila "A13 Write <fuera>/<->/proc/self/cwd>/src/a.ts" "$J"
j_bash "echo x > $OUT/lcwd/src/a.ts"; fila "A14 echo > <fuera>/<->/proc/self/cwd>/src/a.ts (Bash, ancla)" "$J"
j_bash "echo x > $OUT/lcwd/src/a.ts" ""; fila "A15 idem sin cwd en la entrada" "$J"
j_edit "/proc/self/root/proc/self/cwd/requirements/REQ-900.md" "Estado: en-revisión" "Estado: completado"; fila "A16 Edit /proc/self/root/proc/self/cwd/requirements/…" "$J"
j_edit "$OUT/lreq/REQ-900.md" "Estado: en-revisión" "Estado: completado"; fila "A17 control: mismo enlace fuera de /dev" "$J"
echo "== Lo legítimo bajo /dev =="
j_bash "ls -la > /dev/null 2>&1"; fila "N1 > /dev/null" "$J"
j_bash "echo hola > /dev/stderr"; fila "N2 > /dev/stderr" "$J"
j_bash "echo hola | tee /dev/stderr"; fila "N3 tee /dev/stderr" "$J"
j_bash "echo hola > /proc/self/fd/2"; fila "N4 > /proc/self/fd/2" "$J"
j_bash "echo hola 1>&2 2>/dev/fd/1"; fila "N5 2>/dev/fd/1" "$J"
j_write "/dev/null" "$S/ct.txt"; fila "N6 Write /dev/null (coordinadora)" "$J"
j_write "/dev/stderr" "$S/ct.txt"; fila "N7 Write /dev/stderr (movimiento declarado)" "$J"
echo "== Cara (b): proyecto situado bajo /dev/shm =="
PB="$P"
PD="/dev/shm/arnes-r047-proj-$$"; proyecto_nuevo "$PD"
ln -s ../requirements/REQ-900.md "$P/docs/enlace.md"; ln -s ../src/a.ts "$P/docs/a-enlace.ts"
j_edit "$P/docs/enlace.md" "Estado: en-revisión" "Estado: completado"; fila "B1 Edit por enlace último componente (cierra)" "$J"
j_write "$P/docs/a-enlace.ts" "$S/ct.txt"; fila "B2 Write coordinadora por enlace -> src/a.ts" "$J"
j_write "$P/docs/enlace.md" "$S/req-cerrado.txt"; fila "B3 Write REQ cerrado por enlace" "$J"
j_edit "$P/requirements/REQ-901.md" "texto" "texto2"; fila "B4 Edit literal legítimo de REQ existente (allow)" "$J"
j_edit "$P/requirements/REQ-900.md" "Estado: en-revisión" "Estado: completado"; fila "B5 Edit canónico cierra REQ rojo (deny)" "$J"
j_edit "$P/requirements/REQ-901.md" "Estado: en-revisión" "Estado: completado"; fila "B6 Edit cierra REQ verde (allow)" "$J"
j_bash "echo x > src/a.ts"; fila "B7 echo > src/a.ts coordinadora" "$J"
j_write "$P/docs/nuevo.md" "$S/ct.txt"; fila "B8 Write legítimo docs/nuevo.md (allow)" "$J"
echo "== Efecto real del shell en las formas de la cara (a) (árbol aparte) =="
T="$S/efecto-$$"; proyecto_nuevo "$T"; LT="/dev/shm/arnes-r047-t-$$"; ln -s "$T/src" "$LT"
( cd "$T" && echo INTRUSO-shm > "$LT/a.ts"; echo INTRUSO-root >> "/proc/self/root$T/src/a.ts"; echo INTRUSO-cwd >> /proc/self/cwd/src/a.ts )
printf 'src/a.ts:\n'; cat "$T/src/a.ts"; rm -f "$LT"; rm -rf "$T"
