#!/usr/bin/env bash
# t3 — CR en el texto de Bash (P-023-13-A / QA-023-15), delimitador de heredoc con CR (punto 17) y guard-git con
# dos lecturas (P-122-A (1), QA-023-16). Variantes propias del auditor, no copiadas de las baterías de dev/QA.
# Sólo se generan entradas JSON para el hook: aquí no se ejecuta ningún git.
set -u
. /tmp/claude-1000/-home-juan-dev-ArnesJuan-v1-35/498ed6ee-03a0-4ce1-b63b-6612ed12e677/scratchpad/ev8/lib-sonda8.sh
proyecto_nuevo "$S/p3"
ln -s ../src/a.ts "$P/docs/k$CR"
echo "== Destinos con CR (el shell trata el CR como carácter de palabra) =="
j_bash "printf x > docs/k$CR"; fila "K1 printf > docs/k<CR> (enlace a src/a.ts)" "$J"
j_bash "printf x > docs/n.md$CR"; fila "K2 printf > docs/n.md<CR> fuera del ámbito (allow)" "$J"
j_bash "echo x$CR> src/a.ts"; fila "K3 echo x<CR>> src/a.ts (CR antes del >)" "$J"
j_bash "echo x $CR> src/a.ts"; fila "K4 echo x <CR>> src/a.ts" "$J"
j_bash "echo x >$CR src/a.ts"; fila "K5 echo x ><CR> src/a.ts (escribe en '<CR>')" "$J"
j_bash "echo x > src/a.ts$CR"; fila "K6 echo > src/a.ts<CR> (src/* casa)" "$J"
j_bash "echo x > app/a.ts$CR"; fila "K7 echo > app/a.ts<CR> (app/*.ts no casa: K6 declarado)" "$J"
j_bash "echo x | tee src/a.ts$CR"; fila "K8 tee src/a.ts<CR>" "$J"
j_bash "echo x | tee$CR src/a.ts"; fila "K9 tee<CR> src/a.ts (orden inexistente)" "$J"
j_bash "cp /etc/hostname src/a.ts$CR"; fila "K10 cp … src/a.ts<CR>" "$J"
j_bash "sed -i$CR 's/en-revisión/completado/' requirements/REQ-900.md"; fila "K11 sed -i<CR> cierra REQ (sufijo de copia = CR)" "$J"
j_bash "sed -i 's/en-revisión/completado/' requirements/REQ-900.md$CR"; fila "K12 sed -i … REQ-900.md<CR>" "$J"
j_bash "echo ok$CR"$'\n'"echo x > src/a.ts$CR"$'\n'; fila "K13 CRLF de varias líneas, 2ª escribe src/a.ts<CR>" "$J"
j_bash "ls$CR"$'\n'"echo x > src/a.ts"; fila "K14 ls<CR><LF> y luego echo > src/a.ts" "$J"
j_bash "echo x > src/a.ts$CR$CR"; fila "K15 dos CR finales" "$J"
j_bash "$CR"; fila "K16 comando que es sólo un CR (allow)" "$J"
j_bash "ls -la$CR"; fila "K17 ls -la<CR> (allow)" "$J"
echo "== Heredoc con CR en el delimitador (punto 17) y variantes de espacio/comillas =="
j_bash "cat > src/a.ts <<'EOF'$CR"$'\n'"x$CR"$'\n'"EOF$CR"$'\n'; fila "H1 cat > src/a.ts <<'EOF'<CR> (coordinadora)" "$J"
j_bash "cat <<EOF > docs/x.md$CR"$'\n'"x"$'\n'"EOF$CR"$'\n'"echo y > src/a.ts"$'\n'"EOF"$'\n'; fila "H2 <<EOF … cuerpo con EOF<CR>, tras EOF real" "$J"
j_bash "cat << EOF$CR"$'\n'"x"$'\n'"EOF$CR"$'\n'"echo y > src/a.ts"$'\n'; fila "H3 cat << EOF<CR> (espacio antes)" "$J"
j_bash "cat <<-EOF$CR"$'\n'"x"$'\n'"EOF$CR"$'\n'"echo y > src/a.ts"$'\n'; fila "H4 cat <<-EOF<CR>" "$J"
j_bash "cat <<\"EOF\"$CR"$'\n'"x"$'\n'"EOF$CR"$'\n'"echo y > src/a.ts"$'\n'; fila "H5 cat <<\"EOF\"<CR>" "$J"
j_bash "cat <<\\EOF$CR"$'\n'"x"$'\n'"EOF$CR"$'\n'"echo y > src/a.ts"$'\n'; fila "H6 cat <<\\EOF<CR>" "$J"
j_bash "cat <<'EO${CR}F'"$'\n'"x"$'\n'"EO${CR}F"$'\n'"echo y > src/a.ts"$'\n'; fila "H7 cat <<'EO<CR>F' (CR en medio)" "$J"
j_bash "cat <<   EOF$CR"$'\n'"x"$'\n'"EOF$CR"$'\n'"echo y > src/a.ts"$'\n'; fila "H8 cat <<   EOF<CR> (varios espacios)" "$J"
j_bash "cat <<	EOF$CR"$'\n'"x"$'\n'"EOF$CR"$'\n'"echo y > src/a.ts"$'\n'; fila "H9 cat <<<TAB>EOF<CR>" "$J"
j_bash "cat <<EOF;$CR"$'\n'"x"$'\n'"EOF"$'\n'"echo y > src/a.ts"$'\n'; fila "H10 cat <<EOF;<CR> (CR tras metacarácter)" "$J"
j_bash "cat <<EOF"$'\n'"x$CR"$'\n'"EOF"$'\n'; fila "H11 CR sólo en el cuerpo (allow)" "$J"
j_bash "cat > src/a.ts <<'EOF'$CR"$'\n'"x$CR"$'\n'"EOF$CR"$'\n' "$P" desarrollador; fila "H12 H1 por el desarrollador (guard-completado: deny a todos)" "$J"
j_bash "cat <<< x$CR"; fila "H13 here-string <<< x<CR> (no es heredoc)" "$J"
j_bash "cat <<<EOF$CR"; fila "H14 cat <<<EOF<CR> (here-string)" "$J"
echo "== guard-git: dos lecturas =="
j_bash "git stash$CR"; fila "G1 git stash<CR>" "$J"
j_bash "git checkout .$CR"; fila "G2 git checkout .<CR>" "$J"
j_bash "git restore .$CR"$'\n'; fila "G3 git restore .<CR><LF>" "$J"
j_bash "git reset --hard$CR"; fila "G4 git reset --hard<CR>" "$J"
j_bash "git clean -f$CR"; fila "G5 git clean -f<CR>" "$J"
j_bash "git status && git st${CR}ash"; fila "G6 git status && git st<CR>ash" "$J"
j_bash "git -c help.autocorrect=immediate stash$CR"; fila "G7 git -c help.autocorrect=immediate stash<CR>" "$J"
j_bash "git 'stash'$CR"; fila "G8 git 'stash'<CR>" "$J"
j_bash "git \"checkout\" .$CR"; fila "G9 git \"checkout\" .<CR>" "$J"
j_bash "git${CR} reset --hard"; fila "G10 git<CR> reset --hard" "$J"
j_bash "echo git stash$CR"; fila "G11 echo git stash<CR> (no es git; sobredenegación?)" "$J"
j_bash "git log --oneline$CR"; fila "G12 git log<CR> (allow)" "$J"
j_bash "git commit -m \"arreglo$CR\""; fila "G13 git commit -m con CR (allow)" "$J"
j_bash "git stash list$CR"; fila "G14 git stash list<CR> (allow)" "$J"
j_bash "git restore --staged a.txt$CR"; fila "G15 git restore --staged a.txt<CR> (allow)" "$J"
j_bash "git stash$CR" "$P" desarrollador; fila "G16 git stash<CR> por el desarrollador (deny a todos)" "$J"
