#!/usr/bin/env bash
# t6 (= s3 de R-046 re-ejecutada en R-047) — las reparaciones del delta, por muestreo propio: QA-023-13 (CR), QA-023-09 (LF), SEC-117, O-11, SEC-119, CA-60.
set -u
. /tmp/claude-1000/-home-juan-dev-ArnesJuan-v1-35/498ed6ee-03a0-4ce1-b63b-6612ed12e677/scratchpad/ev8/lib-sonda8.sh
proyecto_nuevo "$S/p6"
F="$S/f3-$$"; rm -rf "$F"; mkdir -p "$F/d"; ln -s "$P" "$F/d"$'\r'          # d␍ -> raíz ; d normal
trap 'rm -rf "$F"' EXIT
CR=$'\r'; LF=$'\n'
printf 'x\n' > "$S/ct.txt"
echo "== QA-023-13: cwd = <fuera>/d␍ (enlace a la raíz); <fuera>/d normal =="
j_bash "echo x > src/a.ts" "$F/d$CR"; fila "A1 echo > src/a.ts, coordinadora" "$J"
j_bash "sed -i 's/en-revisión/completado/' requirements/REQ-900.md" "$F/d$CR"; fila "A2 sed -i cierra REQ rojo" "$J"
j_edit "requirements/REQ-900.md" "Estado: en-revisión" "Estado: completado" "$F/d$CR"; fila "A3 Edit relativo cierra REQ rojo" "$J"
j_write "src/a.ts" "$S/ct.txt" "$F/d$CR"; fila "A4 Write relativo src/a.ts coordinadora" "$J"
j_write "$P/docs/legit.md" "$S/ct.txt" "$F/d$CR"; fila "A5 Write ABSOLUTO docs/legit.md (legítimo)" "$J"
j_bash "ls -la" "$F/d$CR"; fila "A6 ls -la (legítimo)" "$J"
j_bash "echo x > src/b.ts" "$F/d$CR" desarrollador; fila "A7 desarrollador echo > src/b.ts relativo" "$J"
echo "== file_path / tool_name con CR =="
ln -s ../src/a.ts "$P/docs/l$CR"
j_write "$P/docs/l$CR" "$S/ct.txt"; fila "B1 Write <raíz>/docs/l␍ (enlace a src/a.ts)" "$J"
j_write "$P/docs/n.md" "$S/ct.txt"; fila "B2 Write <raíz>/docs/n.md (legítimo)" "$J"
jq -n --arg c "$P" --arg fp "$P/requirements/REQ-900.md" '{tool_name:"Edit\r",cwd:$c,tool_input:{file_path:$fp,old_string:"Estado: en-revisión",new_string:"Estado: completado"}}' > "$J"; fila "B3 tool_name Edit␍ cierra REQ rojo" "$J"
jq -n --arg c "$P" --arg fp "$P/src/a.ts" '{tool_name:"Bash\r",cwd:$c,tool_input:{command:"ls",file_path:$fp}}' > "$J"; fila "B4 tool_name Bash␍ + file_path src" "$J"
echo "== QA-023-09: cwd con LF =="
mkdir -p "$F/x${LF}y"
j_edit "$P/requirements/REQ-900.md" "Estado: en-revisión" "Estado: completado" "/tmp${LF}b"; fila "L1 cwd /tmp␊b, Edit canónico cierra REQ rojo" "$J"
j_write "$P/src/a.ts" "$S/ct.txt" "/tmp${LF}b"; fila "L2 cwd /tmp␊b, Write src/a.ts coordinadora" "$J"
j_edit "$P/requirements/REQ-900.md" "no-literal" "Estado: completado" "/tmp${LF}b"; fila "L3 cwd /tmp␊b, Edit no literal (SEC-117)" "$J"
j_write "$P/docs/ok.md" "$S/ct.txt" "$F/x${LF}y"; fila "L4 cwd x␊y real, Write docs (legítimo)" "$J"
j_edit "$P/requirements/REQ-900.md${LF}" "Estado: en-revisión" "Estado: completado"; fila "L5 file_path con LF final" "$J"
echo "== SEC-117 (REQ-023 CA-13) =="
j_edit "$P/requirements/REQ-900.md" "Estado: en-revisi\\u00f3n" "Estado: completado"; fila "S1 old_string con \\u00f3n literal (no está)" "$J"
j_edit "$P/requirements/REQ-901.md" "texto" "texto nuevo"; fila "S2 Edit literal cuerpo REQ verde (legítimo)" "$J"
j_edit "$P/requirements/REQ-901.md" "Estado: en-revisión" "Estado: completado"; fila "S3 Edit literal cierra REQ verde (legítimo)" "$J"
echo "== SEC-119: rutas equivalentes =="
ln -s ../requirements "$P/docs/dreq"; ln -s ../src "$P/docs/dsrc"
j_edit "$P/docs/../requirements/REQ-900.md" "Estado: en-revisión" "Estado: completado"; fila "I1 Edit <raíz>/docs/../requirements" "$J"
j_edit "$P/././requirements/REQ-900.md" "Estado: en-revisión" "Estado: completado"; fila "I2 Edit <raíz>/././requirements" "$J"
j_edit "$P/docs/dreq/REQ-900.md" "Estado: en-revisión" "Estado: completado"; fila "I3 Edit por directorio enlazado" "$J"
j_write "$P/docs/../src/a.ts" "$S/ct.txt"; fila "I4 Write <raíz>/docs/../src/a.ts" "$J"
j_bash "printf x > docs/../src/a.ts"; fila "I5 printf > docs/../src/a.ts" "$J"
j_bash "sed -i 's/en-revisión/completado/' docs/../requirements/REQ-900.md"; fila "I6 sed -i docs/../requirements" "$J"
j_bash "echo x > docs/dsrc/a.ts"; fila "I7 echo > docs/dsrc/a.ts" "$J"
j_write "$P/src/../README.md" "$S/ct.txt"; fila "I8 Write src/../README.md (fuera, movimiento declarado)" "$J"
j_write "$P/docs/nuevo/dir/x.md" "$S/ct.txt"; fila "I9 Write docs/nuevo/dir/x.md (creación legítima)" "$J"
j_write "$P/requirements/nuevo/../REQ-900.md" "$S/req-cerrado.txt" 2>/dev/null
printf '%s' "${REQ_ROJO/en-revisión/completado}" > "$S/req-cerrado.txt"
j_write "$P/requirements/nuevo/../REQ-900.md" "$S/req-cerrado.txt"; fila "I10 Write requirements/<no existe>/../REQ-900" "$J"
echo "== O-11 (CA-45): REQ ilegible =="
printf 'Estado: en-revisi\0ón\nQA: pendiente\n' > "$P/requirements/REQ-902.md"
j_edit "$P/requirements/REQ-902.md" "QA: pendiente" "QA: aprobado"; fila "O1 Edit sobre REQ con NUL (no cierra)" "$J"
printf '%s' "${REQ_ROJO/en-revisión/completado}" > "$S/r902.txt"
j_write "$P/requirements/REQ-902.md" "$S/r902.txt"; fila "O2 Write REQ cerrado en rojo sobre ilegible" "$J"
printf '%s' "${REQ_VERDE/en-revisión/en-progreso}" > "$S/v902.txt"
j_write "$P/requirements/REQ-902.md" "$S/v902.txt"; fila "O3 Write que rehace el ilegible, sin cerrar (salida)" "$J"
echo "== CA-60: manifiesto roto, reparación =="
cp "$P/.arnes/config.json" "$S/cfg.bak"; printf '{roto' > "$P/.arnes/config.json"
printf '%s\n' "$MANIF" > "$S/cfg.txt"
j_write "$P/.arnes/config.json" "$S/cfg.txt"; fila "M1 Write al manifiesto roto (reparación)" "$J"
j_write "$P/docs/../.arnes/config.json" "$S/cfg.txt"; fila "M2 Write al manifiesto por docs/../" "$J"
j_write "$P/src/a.ts" "$S/ct.txt"; fila "M3 Write src/a.ts con manifiesto roto" "$J"
cp "$S/cfg.bak" "$P/.arnes/config.json"
