#!/usr/bin/env bash
# s1 — F3 de CA-47: destinos bajo /dev/ y /proc/ que llegan al archivo protegido por resolución de nombres.
set -u
. /tmp/claude-1000/-home-juan-dev-ArnesJuan-v1-35/498ed6ee-03a0-4ce1-b63b-6612ed12e677/scratchpad/ev/lib-sonda.sh
BASEP="${1:-$S/p1}"
proyecto_nuevo "$BASEP"
L="/dev/shm/arnes-r046-$$"; LS="/dev/shm/arnes-r046-src-$$"
OUT="$S/fuera-$$"; mkdir -p "$OUT"
ln -s "$P/requirements" "$L"; ln -s "$P/src" "$LS"; ln -s "$P/requirements" "$OUT/lreq"; ln -s "$P/src" "$OUT/lsrc"
trap 'rm -f "$L" "$LS"; rm -rf "$OUT"' EXIT
echo "proyecto=$P  enlaces: $L -> requirements ; $LS -> src ; $OUT/lreq, $OUT/lsrc"
echo "== Controles: ruta canónica =="
j_edit "$P/requirements/REQ-900.md" "Estado: en-revisión" "Estado: completado"; fila "C1 Edit canónico cierra REQ rojo" "$J"
printf 'x\n' > "$S/ct.txt"
j_write "$P/src/a.ts" "$S/ct.txt"; fila "C2 Write canónico coordinadora src/a.ts" "$J"
j_bash "sed -i 's/en-revisión/completado/' requirements/REQ-900.md"; fila "C3 sed -i relativo cierra REQ rojo" "$J"
j_bash "echo x > src/a.ts"; fila "C4 echo > src/a.ts coordinadora" "$J"
echo "== SEC-119 fuera del proyecto, enlace NO bajo /dev (controles de que la identidad funciona) =="
j_edit "$OUT/lreq/REQ-900.md" "Estado: en-revisión" "Estado: completado"; fila "O1 Edit por enlace externo" "$J"
j_write "$OUT/lsrc/a.ts" "$S/ct.txt"; fila "O2 Write por enlace externo" "$J"
j_bash "sed -i 's/en-revisión/completado/' $OUT/lreq/REQ-900.md"; fila "O3 sed -i por enlace externo" "$J"
j_bash "echo x > $OUT/lsrc/a.ts"; fila "O4 echo > por enlace externo" "$J"
echo "== /dev/shm: un enlace simbólico corriente en un tmpfs escribible =="
j_edit "$L/REQ-900.md" "Estado: en-revisión" "Estado: completado"; fila "D1 Edit /dev/shm/<enlace>/REQ-900.md" "$J"
j_edit "$L/REQ-900.md" "x-no-literal" "Estado: completado"; fila "D1b Edit no literal (SEC-117) por /dev/shm" "$J"
j_write "$LS/a.ts" "$S/ct.txt"; fila "D2 Write /dev/shm/<enlace>/a.ts coordinadora" "$J"
j_bash "sed -i 's/en-revisión/completado/' $L/REQ-900.md"; fila "D3 sed -i por /dev/shm" "$J"
j_bash "echo x > $LS/a.ts"; fila "D4 echo > por /dev/shm" "$J"
printf '%s' "${REQ_ROJO/en-revisión/completado}" > "$S/req-cerrado.txt"
j_write "$L/REQ-900.md" "$S/req-cerrado.txt"; fila "D5 Write del REQ cerrado por /dev/shm" "$J"
echo "== /proc/self/root y /proc/self/cwd =="
j_edit "/proc/self/root$P/requirements/REQ-900.md" "Estado: en-revisión" "Estado: completado"; fila "R1 Edit /proc/self/root<raíz>/requirements/…" "$J"
j_write "/proc/self/root$P/src/a.ts" "$S/ct.txt"; fila "R2 Write /proc/self/root<raíz>/src/a.ts" "$J"
j_bash "sed -i 's/en-revisión/completado/' /proc/self/root$P/requirements/REQ-900.md"; fila "R3 sed -i /proc/self/root" "$J"
j_bash "echo x > /proc/self/root$P/src/a.ts"; fila "R4 echo > /proc/self/root" "$J"
j_bash "echo x > /proc/self/cwd/src/a.ts"; fila "R5 echo > /proc/self/cwd/src/a.ts (cwd=raíz)" "$J"
j_bash "sed -i 's/en-revisión/completado/' /proc/self/cwd/requirements/REQ-900.md"; fila "R6 sed -i /proc/self/cwd (cwd=raíz)" "$J"
echo "== Lo legítimo bajo /dev (debe seguir pasando) =="
j_bash "ls -la > /dev/null 2>&1"; fila "N1 > /dev/null" "$J"
j_bash "echo hola > /dev/stderr"; fila "N2 > /dev/stderr" "$J"
echo "== El shell, de verdad: ¿escribe en el archivo protegido? (árbol aparte) =="
T="$S/efecto-$$"; proyecto_nuevo "$T"; LT="/dev/shm/arnes-r046-t-$$"; ln -s "$T/src" "$LT"
( cd "$T" && echo INTRUSO-shm > "$LT/a.ts"; echo INTRUSO-proc >> "/proc/self/root$T/src/a.ts" )
printf 'src/a.ts tras escribir por /dev/shm y /proc/self/root:\n'; cat "$T/src/a.ts"; rm -f "$LT"
