#!/usr/bin/env bash
# Re-derivación independiente de la tabla de REQ-023 CA-08 (filas R, A, S, U, F) contra CAND, BASE (713ac68) y N (1.33.2).
. "$(dirname "$0")/qa-lib.sh"
E0='Estado: en-revisión'; EC='Estado: completado'; S0='Sensible a seguridad: sí'; Q0='QA: aprobado'; QP='QA: pendiente'
G0='Seguridad: aprobado'; GP='Seguridad: pendiente'; H0='Hallazgos abiertos: (ninguno)'; HC='Hallazgos abiertos: SEC-1 (contrato)'
R0='Rigor: critico'; RL='Rigor: ligero'; BOM=$'\xef\xbb\xbf'; ZW=$'\xe2\x80\x8b'; NB=$'\xc2\xa0'
fila() { local id="$1" vias="$2" esp="$3" o="${5:-$E0}" n="${6:-$EC}" v; for v in E W; do case "$vias" in *$v*) prueba "$id" "$v" "$4" "$o" "$n" "$esp" ;; esac; done; }
doc "$E0" "$S0" "$Q0" "$G0" "Hallazgos  abiertos: SEC-1 (contrato)" "$R0";                 fila R1 EW deny "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "Hallazgos abiertos: QA-2 (instrumento)" "HALLAZGOS ABIERTOS: SEC-1 (contrato)" "$R0"; fila R2 EW deny "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "${BOM}$HC" "$R0";                                             fila R3 EW deny "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "Hallazgos${ZW} abiertos: SEC-1 (contrato)" "$R0";             fila R4 EW deny "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "Hallazgos${NB}abiertos: SEC-1 (contrato)" "$R0";              fila R5 EW deny "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "- $HC" "$R0";                                                 fila R6 EW deny "$DOC"
doc "$E0" "SENSIBLE A  SEGURIDAD: sí" "$QP" "$GP" "$H0" "$RL";                             fila R7 EW deny "$DOC"
doc "$E0" "${BOM}$S0" "$QP" "$GP" "$H0" "$RL";                                             fila R8 EW deny "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" $'\xc3'"$HC" "$R0";                                            fila R9 EW deny "$DOC"
doc "$E0" "$S0" "qa: pendiente" "$G0" "$H0" "$R0";                                         fila R10 EW deny "$DOC"
doc "$E0" "Sensible a seguridad: no" "$Q0" "$GP" "$H0" "RIGOR: critico";                   fila R11 EW deny "$DOC"
doc "$E0" "$S0" "$QP" "$G0" "$H0" "$R0";                                                   fila R12 E deny "$DOC" "$E0" "ESTADO: completado"
doc "$E0" "$S0" "$QP" "$GP" "$H0" "$RL" "Sensible a seguridad: no";                        fila R13 EW deny "$DOC"
doc "$E0" "$S0" "1. QA: pendiente" "$G0" "$H0" "$R0";                                      fila R14 EW deny "$DOC"
doc "$E0" "$S0" "$QP" "$G0" "$H0" "$R0" "$Q0";                                             fila R15 EW deny "$DOC"
doc "$E0" "$S0" "$Q0" "$Q0" "$G0" "$H0" "$R0";                                             fila R16 EW deny "$DOC"
# R17: Estado canónica y más abajo Estado: completado (el cierre escondido tras «la primera manda»): la edición añade la segunda
doc "$E0" "$S0" "$QP" "$G0" "$H0" "$R0";                                                   fila R17 EW deny "$DOC" "$R0" "$R0"$'\n'"$EC"
doc "$E0" "$S0" "$Q0" "$G0" "${BOM}- $HC" "$R0";                                           fila R18 EW deny "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "$H0" "$R0";                                                   fila A1 EW allow "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "**Hallazgos abiertos:** (ninguno)" "$R0";                     fila A2 EW allow "$DOC"
doc "$E0" "$Q0";                                                                           fila A3 EW allow "$DOC"
doc "$E0" "Módulo: hooks" "Versión destino: 1.35.0" "Nota: la seguridad del estado se revisa aparte." "$S0" "$Q0" "$G0" "$H0" "$R0"; fila A4 EW allow "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "$H0" "$R0" "<!-- Hallazgos  abiertos: SEC-1 (contrato) -->";   fila A5 EW allow "$DOC"
doc "$EC" "$S0" "$Q0" "$G0" "$H0" "$R0" "$Q0";                                             fila A6 E allow "$DOC" "$EC" "Estado: en-progreso"
doc "$E0" "Prioridad: alta" "$S0" "qa: pendiente" "$G0" "$H0" "$R0";                       fila A7 E allow "$DOC" "Prioridad: alta" "Prioridad: media"
DOC="# REQ-950"$'\n'"$E0"$'\n'"$S0"$'\n'"$Q0"$'\n'"$G0"$'\n'"$H0"$'\n'"$R0"$'\n\n## Historia\n\nHallazgos  abiertos: SEC-1 (contrato)\n'; fila A8 EW allow "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "$H0" "**Rigor**: critico";                                   fila A9 EW allow "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "$H0" "$R0" "> Estado: completado";                            fila S1 EW allow "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "$H0" "$R0" "«Estado»: completado";                            fila S2 EW allow "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "$H0" "$R0" "(QA): pendiente";                                 fila S3 EW allow "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "$H0" "$R0" "[Rigor]: ligero";                                 fila S4 EW allow "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "$H0" "$R0" "Q&A: pendiente";                                  fila S5 EW allow "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "$HC" "$R0" "$H0";                                             fila U1 EW deny "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "$HC" "$R0";                                                   fila U2 EW deny "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "$H0" "$R0"; D="${DOC//$'\n'/$'\r\n'}";                        fila U3-A1crlf EW allow "$D"
doc "$E0" "${BOM}$S0" "$QP" "$GP" "$H0" "$RL"; D="${DOC//$'\n'/$'\r\n'}";                  fila U3-R8crlf EW deny "$D"
doc "$E0" "$S0" "$Q0" "$G0" "Hallazgоs abiertos: SEC-1 (contrato)" "$R0";                  fila F1 EW allow "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "Hallazgo abierto: SEC-1 (contrato)" "$R0";                    fila F2 EW allow "$DOC"
P=''; for i in $(seq 90); do P+="$ZW"; done
doc "$E0" "$S0" "$Q0" "$G0" "${P}$HC" "$R0";                                               fila F3 EW allow "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "Hallazgos abiertos： SEC-1 (contrato)" "$R0";                 fila F4 EW allow "$DOC"
doc "$E0" "$S0" "$Q0" "$G0" "-${NB}$HC" "$R0";                                             fila F5 EW allow "$DOC"
echo "TOTAL=$TOT INESPERADOS=$MAL"
