#!/usr/bin/env bash
# Batería del desarrollador para QA-023-09: saltos de línea en cada campo que lee arnes_parse_input,
# en los cuatro árboles. Una corrida, sin repetir.
source /tmp/claude-1000/-home-juan-dev-ArnesJuan-v1-35/498ed6ee-03a0-4ce1-b63b-6612ed12e677/scratchpad/evidencia-dev-r6/lib-r6.sh
W=$(mktemp -d /tmp/r6bat-XXXXXX); PRJ="$W/p"; mkproj "$PRJ"; P="$PRJ"; R="$P/requirements"; F="$W/fuera"; mkdir -p "$F"
req "$R/REQ-1.md"; req "$R/REQ-2.md" en-revisión aprobado
printf '# REQ-3\nEstado: en-revisión (tras “R-4”)\nSensible a seguridad: sí\nQA: pendiente\nSeguridad: pendiente\nRigor: critico\n' > "$R/REQ-3.md"
{ printf '# REQ-4 '; printf '\000'; printf ' nota\nEstado: en-revisión\nQA: pendiente\n'; } > "$R/REQ-4.md"
ln -s ../requirements/REQ-1.md "$P/docs/l-req.md"; ln -s ../src/a.ts "$P/docs/l-src.md"
mkdir -p "$P/docs/a"$'\n'"b" "$P/src/s"$'\n'"t" "$P/requirements/r"$'\n'"q"
NLD="$P/docs/a"$'\n'"b"     # directorio REAL con salto de línea, fuera del ámbito
NLS="$P/src/s"$'\n'"t"      # directorio REAL con salto de línea, dentro de src/
NLR="$P/requirements/r"$'\n'"q"
cierre() { j Edit "$1" "${3:--}" "file_path=${2:-$R/REQ-1.md}" 'old_string=Estado: en-revisión' 'new_string=Estado: completado'; }
echo "== proyecto: $P (manifiesto: globs src/*, app/*.ts, cfg/main.json) =="
echo "== A: cwd con salto de línea (la regresión), la escritura por su ruta canónica =="
quad "A1 Edit cierre REQ critico, cwd=/tmp\\nb"            guard.sh "$(cierre $'/tmp\nb')"
quad "A1g guard-completado.sh a solas"                       guard-completado.sh "$(cierre $'/tmp\nb')"
quad "A2 Edit cierre, cwd=<raíz>\\n (salto final)"          guard.sh "$(cierre "$P"$'\n')"
quad "A3 Edit cierre, cwd=<raíz>\\n<raíz>/docs"             guard.sh "$(cierre "$P"$'\n'"$P/docs")"
quad "A4 Edit cierre, cwd=dir real con salto ($NLD)"         guard.sh "$(cierre "$NLD")"
quad "A5 Write coordinadora src/a.ts, cwd=/tmp\\nb"         guard.sh "$(j Write $'/tmp\nb' - "file_path=$P/src/a.ts" content=x)"
quad "A5g guard-codigo.sh a solas"                           guard-codigo.sh "$(j Write $'/tmp\nb' - "file_path=$P/src/a.ts" content=x)"
quad "A6 Write coordinadora src/a.ts, cwd=<raíz>\\n"        guard.sh "$(j Write "$P"$'\n' - "file_path=$P/src/a.ts" content=x)"
quad "A7 Edit src/a.ts coordinadora, cwd=dir real NLD"       guard.sh "$(j Edit "$NLD" - "file_path=$P/src/a.ts" old_string=x new_string=y)"
quad "A8 MultiEdit cierre, cwd=/tmp\\nb"                    guard.sh "$(jq -cn --arg c $'/tmp\nb' --arg f "$R/REQ-1.md" '{tool_name:"MultiEdit",cwd:$c,tool_input:{file_path:$f,edits:[{old_string:"Estado: en-revisión",new_string:"Estado: completado"}]}}')"
quad "A9 SEC-117 no reconstruible, cwd=/tmp\\nb"            guard.sh "$(j Edit $'/tmp\nb' - "file_path=$R/REQ-3.md" 'old_string=en-revisión (tras "R-4")' new_string=completado)"
quad "A10 CA-49 (i) enlace dentro, cwd=/tmp\\nb"            guard.sh "$(cierre $'/tmp\nb' "$P/docs/l-req.md")"
quad "A11 REQ con NUL, Edit sin estado, cwd=/tmp\\nb"       guard.sh "$(j Edit $'/tmp\nb' - "file_path=$R/REQ-4.md" old_string=nota new_string=otra)"
quad "A12 Bash sed canónico absoluto, cwd=/tmp\\nb"         guard.sh "$(j Bash $'/tmp\nb' - "command=sed -i 's/en-revisión/completado/' $R/REQ-1.md")"
quad "A13 Bash printf > <raíz>/src/a.ts abs, cwd=/tmp\\nb"  guard.sh "$(j Bash $'/tmp\nb' - "command=printf x > $P/src/a.ts")"
quad "A14 Bash printf > ../../src/a.ts, cwd=NLD real"        guard.sh "$(j Bash "$NLD" - 'command=printf x > ../../src/a.ts')"
quad "A15 Bash printf > a.ts, cwd=NLS real (dentro de src)"  guard.sh "$(j Bash "$NLS" - 'command=printf x > a.ts')"
quad "A16 Bash sed REQ relativo, cwd=NLR real"               guard.sh "$(j Bash "$NLR" - "command=sed -i 's/x/completado/' REQ-9.md")"
quad "A17 Write coordinadora a.ts relativa?, cwd=NLS (Edit exige abs; inyectada)" guard.sh "$(j Write "$NLS" - "file_path=a.ts" content=x)"
echo "== A-control: lo legítimo con el MISMO cwd de varias líneas =="
quad "AC1 desarrollador Write src/a.ts, cwd=/tmp\\nb"        guard.sh "$(j Write $'/tmp\nb' desarrollador "file_path=$P/src/a.ts" content=x)"
quad "AC2 desarrollador Bash printf > a.ts, cwd=NLS"         guard.sh "$(j Bash "$NLS" desarrollador 'command=printf x > a.ts')"
quad "AC3 coordinadora Write docs/n.md, cwd=/tmp\\nb"        guard.sh "$(j Write $'/tmp\nb' - "file_path=$P/docs/n.md" content=x)"
quad "AC4 coordinadora Bash echo > n.md, cwd=NLD real"        guard.sh "$(j Bash "$NLD" - 'command=echo x > n.md')"
quad "AC5 coordinadora Bash echo > src/a.ts, cwd=NLD real (designa NLD/src/a.ts)" guard.sh "$(j Bash "$NLD" - 'command=echo x > src/a.ts')"
quad "AC6 cierre de REQ en verde, cwd=/tmp\\nb"              guard.sh "$(cierre $'/tmp\nb' "$R/REQ-2.md")"
quad "AC7 cierre de REQ en verde, cwd=NLD real"              guard.sh "$(cierre "$NLD" "$R/REQ-2.md")"
quad "AC8 Bash ls -la, cwd=/tmp\\nb"                         guard.sh "$(j Bash $'/tmp\nb' - 'command=ls -la')"
quad "AC9 Edit literal sin estado REQ-1, cwd=/tmp\\nb"        guard.sh "$(j Edit $'/tmp\nb' - "file_path=$R/REQ-1.md" old_string=nota new_string=otra)"
echo "== B: salto de línea en el file_path =="
quad "B1 Write coord <raíz>/src/a.ts\\n (src/*)"            guard.sh "$(j Write "$P" - "file_path=$P/src/a.ts"$'\n' content=x)"
quad "B2 Write coord <raíz>/app/a.ts\\n (app/*.ts)"         guard.sh "$(j Write "$P" - "file_path=$P/app/a.ts"$'\n' content=x)"
quad "B3 Write coord <raíz>/cfg/main.json\\n (exacto)"      guard.sh "$(j Write "$P" - "file_path=$P/cfg/main.json"$'\n' content=x)"
quad "B4 Write coord <raíz>/cfg/main.json\\nx"              guard.sh "$(j Write "$P" - "file_path=$P/cfg/main.json"$'\n'x content=x)"
quad "B5 Edit cierre <REQ>\\n"                              guard.sh "$(cierre "$P" "$R/REQ-1.md"$'\n')"
quad "B6 Edit creación old='' sin terminal <REQ>\\n"        guard.sh "$(j Edit "$P" - "file_path=$R/REQ-1.md"$'\n' old_string= 'new_string=# nota')"
quad "B7 Write <REQ>\\n con terminal y QA pendiente"         guard.sh "$(j Write "$P" - "file_path=$R/REQ-1.md"$'\n' $'content=# R\nEstado: completado\nSensible a seguridad: sí\nQA: pendiente\n')"
quad "B8 Write <REQ>\\n sin terminal"                       guard.sh "$(j Write "$P" - "file_path=$R/REQ-1.md"$'\n' $'content=# R\nEstado: borrador\n')"
quad "B9 Edit cierre por enlace docs/l-req.md\\n"            guard.sh "$(cierre "$P" "$P/docs/l-req.md"$'\n')"
quad "B10 O-16 file_path=<fuera>\\n<REQ>"                    guard.sh "$(cierre "$P" "$F/x.md"$'\n'"$R/REQ-1.md")"
quad "B11 Write coord <raíz>/docs/x\\n/../../src/a.ts"       guard.sh "$(j Write "$P" - "file_path=$P/docs/x"$'\n'"/../../src/a.ts" content=x)"
quad "B12 Edit cierre <raíz>/docs/x\\n/../../requirements/REQ-1.md" guard.sh "$(cierre "$P" "$P/docs/x"$'\n'"/../../requirements/REQ-1.md")"
quad "B13 desarrollador Write <raíz>/app/a.ts\\n"            guard.sh "$(j Write "$P" desarrollador "file_path=$P/app/a.ts"$'\n' content=x)"
quad "B14 Write coord <raíz>/docs/n.md\\n (fuera)"            guard.sh "$(j Write "$P" - "file_path=$P/docs/n.md"$'\n' content=x)"
quad "B15 Write coord dentro de NLS: <raíz>/src/s\\nt/a.ts"  guard.sh "$(j Write "$P" - "file_path=$NLS/a.ts" content=x)"
quad "B16 Edit cierre REQ en NLR: <raíz>/requirements/r\\nq/R.md" guard.sh "$(req "$NLR/R.md"; cierre "$P" "$NLR/R.md")"
echo "== C: salto de línea en tool_name, agent_id, agent_type =="
quad "C1 agent_type='desarrollador\\n' Write src/a.ts"       guard.sh "$(j Write "$P" $'desarrollador\n' "file_path=$P/src/a.ts" content=x)"
quad "C2 agent_type='qa-tester\\ndesarrollador' Write src"   guard.sh "$(j Write "$P" $'qa-tester\ndesarrollador' "file_path=$P/src/a.ts" content=x)"
quad "C3 agent_type='desarrollador\\nqa' Write src"          guard.sh "$(j Write "$P" $'desarrollador\nqa' "file_path=$P/src/a.ts" content=x)"
quad "C4 agent_id='a\\n1' (coordinadora no) Write src"       guard.sh "$(jq -cn --arg f "$P/src/a.ts" --arg c "$P" '{tool_name:"Write",cwd:$c,agent_id:"a\n1",agent_type:"qa-tester",tool_input:{file_path:$f,content:"x"}}')"
quad "C5 tool_name='Write\\n' coordinadora src/a.ts"         guard.sh "$(j $'Write\n' "$P" - "file_path=$P/src/a.ts" content=x)"
quad "C6 tool_name='Bash\\n' echo x > src/a.ts"              guard.sh "$(j $'Bash\n' "$P" - 'command=echo x > src/a.ts')"
quad "C7 tool_name='Edit\\n' cierre REQ"                     guard.sh "$(j $'Edit\n' "$P" - "file_path=$R/REQ-1.md" 'old_string=Estado: en-revisión' 'new_string=Estado: completado')"
echo "== D: el command con saltos (último campo) y campos no-cadena =="
quad "D1 Bash multilínea con escritura protegida al final"   guard.sh "$(j Bash "$P" - $'command=ls\n\necho x > src/a.ts\n\n')"
quad "D2 Bash multilínea legítimo"                          guard.sh "$(j Bash "$P" - $'command=ls\necho x > docs/n.md\n')"
quad "D3 file_path numérico (Write)"                        guard.sh "$(jq -cn --arg c "$P" '{tool_name:"Write",cwd:$c,tool_input:{file_path:5,content:"x"}}')"
quad "D4 file_path objeto (Write)"                          guard.sh "$(jq -cn --arg c "$P" '{tool_name:"Write",cwd:$c,tool_input:{file_path:{"a":["src/a.ts"]},content:"x"}}')"
quad "D5 cwd numérico, Bash relativo src/a.ts"              guard.sh "$(jq -cn '{tool_name:"Bash",cwd:5,tool_input:{command:"echo x > src/a.ts"}}')"
echo "MOVIMIENTOS deny->allow (contados por árbol de comparación): $NMOV_DA ; allow->deny frente a 43b948a: $NMOV_AD"
rm -rf "$W"
